unit TestForm;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Vcl.Dialogs, Winapi.Windows, System.SysUtils, Vcl.Graphics,
  System.Variants, Form.Principal, Winapi.Messages, Vcl.StdCtrls, Vcl.Controls,
  Vcl.Forms, System.Classes;

type
  // Test methods for class TfrmPrincipal

  TestTfrmPrincipal = class(TTestCase)
  strict private
    FfrmPrincipal: TfrmPrincipal;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestButton1Click;
  end;

implementation

procedure TestTfrmPrincipal.SetUp;
begin
  FfrmPrincipal := TfrmPrincipal.Create(nil);
end;

procedure TestTfrmPrincipal.TearDown;
begin
  FfrmPrincipal.Free;
  FfrmPrincipal := nil;
end;

procedure TestTfrmPrincipal.TestButton1Click;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmPrincipal.Button1Click(Sender);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTfrmPrincipal.Suite);
end.

