CREATE TABLE CLIENTE (
    ID_CLIENTE        INTEGER NOT NULL,
    CODIGO            INTEGER,
    NOME              VARCHAR(200),
    DATA_CADASTRO     TIMESTAMP,
    SALDO_DISPONIVEL  NUMERIC(15,2)
);

CREATE SEQUENCE GEN_CLIENTE;
ALTER SEQUENCE GEN_CLIENTE RESTART WITH 0;

CREATE TABLE PEDIDOS (
    ID_PEDIDO      INTEGER NOT NULL,
    ID_CLIENTE     INTEGER,
    DATA_CADASTRO  TIMESTAMP,
    VALOR_TOTAL    NUMERIC(15,2),
    QTD_ITENS      INTEGER
);


CREATE SEQUENCE GEN_PEDIDOS;
ALTER SEQUENCE GEN_PEDIDOS RESTART WITH 0;