unit Classe.Root;

{*******************************************************************************
    Generated By   : JsonToDelphiClass - 0.65
    Project link   : https://github.com/PKGeorgiev/Delphi-JsonToDelphiClass
    Generated On   : 2019-05-25 15:28:02

    Created By     : Petar Georgiev - (http://pgeorgiev.com)
    Adapted Web By : Marlon Nardi - (http://jsontodelphi.com)
*******************************************************************************}

interface

uses Generics.Collections, Rest.Json, System.SysUtils;

type
  TRootClass = class
  private
    FBalance: Extended;
    FBalanceSat: Extended;
    FCashAddress: String;
    FCurrentPage: Extended;
    FLegacyAddress: String;
    FPagesTotal: Extended;
    FSlpAddress: String;
    FTotalReceived: Extended;
    FTotalReceivedSat: Extended;
    FTotalSent: Extended;
    FTotalSentSat2: Extended;
    FTransactions: TArray<String>;
    FTxApperances: Extended;
    FUnconfirmedBalance: Extended;
    FUnconfirmedBalanceSat: Extended;
    FUnconfirmedTxApperances: Extended;
  public
    property balance: Extended read FBalance write FBalance;
    property balanceSat: Extended read FBalanceSat write FBalanceSat;
    property cashAddress: String read FCashAddress write FCashAddress;
    property currentPage: Extended read FCurrentPage write FCurrentPage;
    property legacyAddress: String read FLegacyAddress write FLegacyAddress;
    property pagesTotal: Extended read FPagesTotal write FPagesTotal;
    property slpAddress: String read FSlpAddress write FSlpAddress;
    property totalReceived: Extended read FTotalReceived write FTotalReceived;
    property totalReceivedSat: Extended read FTotalReceivedSat write FTotalReceivedSat;
    property totalSent: Extended read FTotalSent write FTotalSent;
    property totalSentSat2: Extended read FTotalSentSat2 write FTotalSentSat2;
    property transactions: TArray<String> read FTransactions write FTransactions;
    property txApperances: Extended read FTxApperances write FTxApperances;
    property unconfirmedBalance: Extended read FUnconfirmedBalance write FUnconfirmedBalance;
    property unconfirmedBalanceSat: Extended read FUnconfirmedBalanceSat write FUnconfirmedBalanceSat;
    property unconfirmedTxApperances: Extended read FUnconfirmedTxApperances write FUnconfirmedTxApperances;
    function ToJsonString: string;
    class function FromJsonString(AJsonString: string): TRootClass;
  end;

implementation

{TRootClass}


function TRootClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TRootClass.FromJsonString(AJsonString: string): TRootClass;
begin
  try
  result := TJson.JsonToObject<TRootClass>(AJsonString)
  except
    on E: Exception do
      raise Exception.Create('Erro ao realizar parser: "' + E.QualifiedClassName + ' - ' + E.Message + '"');
  end;
end;

end.
