CREATE TABLE CATEGORIA(ID INT PRIMARY KEY, DESCRICAO VARCHAR(100));
CREATE TABLE PRODUTO(ID INT PRIMARY KEY, DESCRICAO VARCHAR(100) NOT NULL, ID_CATEGORIA INT);

ALTER TABLE PRODUTO ADD CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID);
