CREATE DATABASE "C:\Users\Aluno\Desktop\exemplos-delphi\Capitulo4\Win32.6\FB.fdb" page_size 8192
user 'SYSDBA' password 'masterkey';

CREATE TABLE ORDERS (
    ORDERNO        INTEGER NOT NULL,
    CUSTNO         INTEGER,
    SALEDATE       TIMESTAMP,
    SHIPDATE       TIMESTAMP,
    EMPNO          INTEGER,
    SHIPTOCONTACT  VARCHAR(40),
    SHIPTOADDR1    VARCHAR(40),
    SHIPTOADDR2    VARCHAR(40),
    SHIPTOCITY     VARCHAR(40),
    SHIPTOSTATE    VARCHAR(40),
    SHIPTOZIP      VARCHAR(40),
    SHIPTOCOUNTRY  VARCHAR(40),
    SHIPTOPHONE    VARCHAR(40),
    SHIPVIA        VARCHAR(40),
    PO             VARCHAR(40),
    TERMS          VARCHAR(40),
    PAYMENTMETHOD  VARCHAR(40),
    ITEMSTOTAL     NUMERIC(12,2),
    TAXRATE        NUMERIC(12,2),
    FREIGHT        NUMERIC(12,2),
    AMOUNTPAID     NUMERIC(12,2)
);

ALTER TABLE ORDERS ADD PRIMARY KEY (ORDERNO);

CREATE TABLE ITEMS (
    ORDERNO   INTEGER NOT NULL,
    ITEMNO    INTEGER NOT NULL,
    PARTNO    INTEGER,
    QTY       INTEGER,
    DISCOUNT  NUMERIC(12,2)
);

ALTER TABLE ITEMS ADD CONSTRAINT PK_ITEMS PRIMARY KEY (ITEMNO, ORDERNO);