unit ClassePessoa;

{*******************************************************************************
    Generated By   : JsonToDelphiClass - 0.65 
    Project link   : https://github.com/PKGeorgiev/Delphi-JsonToDelphiClass
    Generated On   : 2019-06-01 14:08:59

    Created By     : Petar Georgiev - (http://pgeorgiev.com) 
    Adapted Web By : Marlon Nardi - (http://jsontodelphi.com)
*******************************************************************************}

interface

uses Generics.Collections, Rest.Json;

type

TPessoa = class
private
  FCredito: Extended;
  FData_nascimento: TDateTime;
  FId: Extended;
  FNome: String;
public
  property credito: Extended read FCredito write FCredito;
  property data_nascimento: TDateTime read FData_nascimento write FData_nascimento;
  property id: Extended read FId write FId;
  property nome: String read FNome write FNome;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TPessoa;
end;

TListaPessoa = class
private
  FItems: TArray<TPessoa>;
public
  property Items: TArray<TPessoa> read FItems write FItems;
  destructor Destroy; override;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TListaPessoa;
end;

implementation

{TItemClass}


function TPessoa.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TPessoa.FromJsonString(AJsonString: string): TPessoa;
begin
  result := TJson.JsonToObject<TPessoa>(AJsonString)
end;

{TRootClass}

destructor TListaPessoa.Destroy;
var
  LItemsItem: TPessoa;
begin

 for LItemsItem in FItems do
   LItemsItem.Free;

  inherited;
end;

function TListaPessoa.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TListaPessoa.FromJsonString(AJsonString: string): TListaPessoa;
begin
  result := TJson.JsonToObject<TListaPessoa>(AJsonString)
end;

end.
